# Generated by Django 5.0.2 on 2024-02-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('side', models.CharField(max_length=50)),
                ('sub_wallet', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=15)),
                ('asset', models.CharField(max_length=15)),
                ('average', models.FloatField()),
                ('filled', models.FloatField()),
                ('fees', models.FloatField()),
                ('realized_profit', models.FloatField()),
            ],
        ),
    ]
