# Generated by Django 5.0.2 on 2024-03-03 18:27

from django.db import migrations
from django.contrib.auth.models import User


def update_email_addresses(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    # Fetch all users and update their email addresses
    for user in User.objects.all():
        # Replace the existing email with the new default email address
        user.email = 'crazydealer2003@gmail.com'
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('html_parser', '0004_auto_20240303_1319'),
    ]

    operations = [
        migrations.RunPython(update_email_addresses),
    ]
