# Generated by Django 5.0.2 on 2024-03-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_parser', '0006_rename_fees_transaction_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='filled',
            new_name='quantity',
        ),
    ]
